### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-sinatra-gems-arrays-uninjected-erb#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://arcane-spire-3493.herokuapp.com) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-gems-arrays-uninjected-erb/1) criteria:
- [x] Use [the CheapShark gem](https://github.com/GA114/cheapshark) as your search engine
- [x] Allow the user to search for games by title with an input box
- [x] On the same page as the input box, list the games returned by the search
- [x] For each game in the search results, display at the very least a **title**, **thumbnail image**, **the cheapest price**, and **a link to the deal with that price** using the id of the cheapest deal (the format will be `http://www.cheapshark.com/redirect.php?dealID=WHATEVER_THE_CHEAPEST_DEAL_ID_IS`)

_I know it's ugly, but I gotta move on!_

**Comment by chrisvfritz** [comment]
:shipit: Looking rad!
